### ISSUE TITLE
Feedback from Iker

### ISSUE THREAD

**Issue by rivasiker** [aumath-advancedr2019/phastypdist#1]
# 1. Purpose of the package

The purpose is stated in the package help file. However, I am still not sure whether the main purpose is to provide the user with general functions for phase-type distributions, or if the package's main goal is to apply these functions for biological problems.

# 2. Completeness

I specially liked that you included the data for continuous and discrete phase-type distributions as R datasets :). Also, all details in the description file seem to be complete.

# 3. Code quality and sophistication

* The package installs without problems and runs very smoothly. 

* It looks like the `dphasetype()` and `var()` don't work for discphasetype objects.

* It would be nice if you could vectorize `dphasetype()` and related functions, such that for example `dphasetype(a, c(1,2,3,4))` could be executed. It would also be more intuitive if you could swap the order of those arguments, so that `dphasetype(x, object)` like in `dnorm(x, ...)`.

# 4. Documentation 

* The documentation is very thorough. However, sometimes I would appreciate more simple examples in the help files. Maybe it's just me, but I would prefer to have a simple example in the help file, and more elaborate examples in the vignette.

* The vignette is not included in the package. To have a look at it I had to knit it myself. 

* The vignette is very thorough too, with a lot of theoretical background and useful examples. However, if the aim of your package is to help bioinformaticians, I think the theoretical background might be too exhaustive. I believe it might be a good idea to have two separate vignettes: one that explains how to use the package even if the user doesn't have a strong mathematical background, and another one that explains phase-type theory in depth for those users that are interested.

# 5. Interface

* The functions and methods feel very natural to use. The have few arguments and can be run easily. 

* If anything, I wouldn't include the function `dSegregatingSites()`, because the user can always create a discphasetype object using `SiteFrequencies()` and then pass it to `dphasetype()`.

# 7. Conclusion 

I really liked the package, specially its smoothness and efficiency. I would add a vignette for those bioinformaticians that struggle with the math (like me :P), but otherwise it's very complete and useful.

**Comment by JetteS** [comment]
Thank you for your feedback Iker!

I have already incorporated some of your comments in the package.
`Dphasetype()` and `var()` should now work for `discphasetype` objects, and the functions `dphasetype()`, `pphasetype()` and `qphasetype()` have been vectorized. 

I would like to swap the order of the arguments in `dphasetype()` and the related functions, but then the functions return errors. It seems as if the generic functions looks at the class of the first argument. So if `x` is the first argument, the classes are no longer `discphasetype` or `contphasetype` but `c(‚double‘, ‚numeric‘)`... 

Regarding your feedback on our vignette, I will definitely talk about it with Peter!

Jette

**Comment by rivasiker** [comment]
Hello!

Regarding the swapping of the arguments in `dphasetype()` and similar, we had the same problem. I haven't looked at your source code, but I'm pretty sure that you are implementing them as methods instead of plain functions. Our solution was to define `dphasetype()` as a normal function with an if statement to determine the class of the object first, and then compute the distribution for the continuous or the discrete based on the conditional statement. 

Best regards,

Iker.

**Comment by rivasiker** [comment]
I think I found a little error in the `rphasetype` method for the `contphasetype` function. You wrote that `IntenseMat <- cbind(T.mat, 1-rowSums(T.mat))`, but shouldn't it be `IntenseMat <- cbind(T.mat, -rowSums(T.mat))` in the case of continuous phase-type distributions?

**Comment by JetteS** [comment]
You are absolutely right! Thank you :-)

**Comment by ute** [comment]
I really like your professional discussion here, @JetteS  and @rivasiker :-)
